packet:
  charset: "US_ASCII"

database:
  jdbcUrl: "jdbc:postgresql://localhost:5432/maplestory"
  username: "postgres"
  password: "password"
  maximumPoolSize: 10

loginServer:
  port: 8484
  idleTimeSeconds: 30

world:
  channelCount: 2

debug:
  recordPacket: true